name: Docker Build and Push to ACR

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
  IMAGE_NAME: "your-image-name"
  IMAGE_TAG: "latest"

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      # 1. 检查磁盘空间
      - name: Check Disk Space Before Cleanup
        run: |
          echo "Before freeing up disk space"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      # 2. 增加可用磁盘空间
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 128
          remove-dotnet: 'true'
          remove-haskell: 'true'
          build-mount-path: '/var/lib/docker/'

      # 3. 重启 Docker 服务
      - name: Restart Docker
        run: sudo service docker restart

      # 4. 再次检查磁盘空间
      - name: Check Disk Space After Cleanup
        run: |
          echo "After freeing up disk space"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      # 5. 登录到 ACR
      - name: Login to ACR
        run: |
          echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login --username ${{ secrets.ALIYUN_REGISTRY_USER }} ${{ env.ALIYUN_REGISTRY }} --password-stdin

      # 6. 构建 Docker 镜像
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAME_SPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      # 7. 推送 Docker 镜像到 ACR
      - name: Push Docker Image
        run: |
          docker push ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAME_SPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
